In [3]:
import seaborn
import imfp
import matplotlib.pyplot as plt 
import pandas as pd 
#import dask.dataframe as dd

pd.options.display.max_colwidth=200
imfp.set_imf_wait_time(3)

In [4]:
# Search for desired database
databases = imfp.imf_databases()
databases[databases.description.str.contains("Balance")]

,database_id,description
0,BOP_2017M06,"Balance of Payments (BOP), 2017 M06"
1,BOP_2020M3,"Balance of Payments (BOP), 2020 M03"
2,BOP_2017M11,"Balance of Payments (BOP), 2017 M11"
4,GFSMAB2016,"Government Finance Statistics Yearbook (GFSY 2016), Main Aggregates and Balances"
5,BOP_2019M12,"Balance of Payments (BOP), 2019 M12"
...,...,...
299,BOPAGG,"Balance of Payments (BOP), World and Regional Aggregates"
304,BOP,Balance of Payments (BOP)
313,BOPSDMXUSD,"Balance of Payments (BOP), Global SDMX (US Dollars)"
319,GFSIBS,"Government Finance Statistics (GFS), Integrated Balance Sheet (Stock Positions and Flows in Assets and Liabilities)"
320,GFSMAB,"Government Finance Statistics (GFS), Main Aggregates and Balances"

In [5]:
# Name of chosen database to use (ID)
database_id = "IFS" #BOP, BOPAGG, BOPSDMXUSD

In [6]:
# Load data set options params: dataset_params via imf_parameters("IFS")
dataset_params = imfp.imf_parameters(database_id) # Load this particular dataset all possible features
dataset_params

{'freq':   input_code description
 0          A      Annual
 1          M     Monthly
 2          Q   Quarterly,
 'ref_area':     input_code                                       description
 0           AF                                       Afghanistan
 1           AL                                           Albania
 2           DZ                                           Algeria
 3           AD                                           Andorra
 4           AO                                            Angola
 ..         ...                                               ...
 266     1C_SRF                                     SRF Countries
 267         F6                                Sub-Saharan Africa
 268         7A  WAEMU (West African Economic and Monetary Union)
 269        A10                                Western Hemisphere
 270        W00                   All Countries, excluding the IO

 [271 rows x 2 columns],
 'indicator':              input_code  \
 0            NFIAXD_XDC
 1         NFIAXD_SA_XDC
 2        NFIAXD_NSA_XDC
 3          NFIAXD_R_XDC
 4       NFIAXD_R_SA_XDC
 ...                 ...
 1676          LU_PE_NUM
 1677   LU_PE_PC_CP_A_PT
 1678     LU_PE_PC_PP_PT
 1679  1C_ALL_INDICATORS
 1680                MFS

                                                                                     description
 0                          Acquisitions less Disposals of Valuables, Nominal, Domestic Currency
 1     Acquisitions less Disposals of Valuables, Nominal, Seasonally Adjusted, Domestic Currency
 2              Acquisitions less Disposals of Valuables, Nominal, Unadjusted, Domestic Currency
 3                             Acquisitions less Disposals of Valuables, Real, Domestic Currency
 4        Acquisitions less Disposals of Valuables, Real, Seasonally Adjusted, Domestic Currency
 ...                                                                                         ...
 1676                                                           Unemployment, Persons, Number of
 1677      Unemployment, Persons, Percentage change, corresponding period previous year, Percent
 1678                         Unemployment, Persons, Percentage change, previous period, Percent
 1679                                                                             All Indicators
 1680                                                    Monetary and Financial Statistics (MFS)

 [1681 rows x 2 columns]}

In [7]:
# Indicator searcher: search_id.description.str.contains("Gross Capital Formation")
search_id = dataset_params["indicator"]
search_params_particular = search_id[search_id.description.str.contains("Mont")]
search_params_particular

,input_code,description
218,FII_3M_PA,"Financial, Interest Rates, 3-Month Interbank Interest, Percent per annum"
259,FIHN_NFC_L_OT_O1MILL_3M_1Y_PA,"Financial, Interest Rates, Harmonized Euro Area Rates, New Business, Loans, Non-financial Corporations, Other Than Bank Overdrafts, Over EUR 1 Million, Over 3 Months and up to 1 Year, Percent per ..."
269,FILED_3M_PA,"Financial, Interest Rates, London Eurodollar Deposit Rate, Three-Month, Percent per annum"
270,FILIBOR_1M_PA,"Financial, Interest Rates, London Interbank Offer Rate, One-Month, Percent per annum"
273,FILIBOR_6M_PA,"Financial, Interest Rates, London Interbank Offer Rate, Six-Month, Percent per annum"

In [10]:
# Set some country ref_area_id
country_names = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BR": "Brazil",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Cabo Verde",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "KM": "Comoros",
    "CD": "Congo (the Democratic Republic of the)",
    "CG": "Congo",
    "CR": "Costa Rica",
    "CI": "CÃ´te d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "CuraÃ§ao",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran (Islamic Republic of)",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KR": "Korea (the Republic of)",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MX": "Mexico",
    "MD": "Moldova (the Republic of)",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "MK": "North Macedonia",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "QA": "Qatar",
    "RE": "RÃ©union",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "SD": "Sudan",
    "SR": "Suriname",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic",
    "TW": "Taiwan (Province of China)",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom of Great Britain and Northern Ireland",
    "US": "United States of America",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela (Bolivarian Republic of)",
    "VN": "Viet Nam",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}
ref_area_id = list(country_names.keys())

In [13]:
# ID params of all indicators we want to data for search: indicator
indicator_id = ["IAFR_BP6_USD","ILFR_BP6_USD","BCAXF_BP6_USD","BKAA_BP6_USD","BFXF_BP6_USD","BTRUE_BP6_USD","BEF_BP6_USD","FASF_USD","FASF_XDC","BOPFR_BP6_USD","PXP_IX","PMP_IX","NGDP_SA_XDC",'NCP_SA_XDC','NCGG_SA_XDC', 'NFI_SA_XDC', 'NINV_SA_XDC', 'NX_SA_XDC', 'NM_SA_XDC', 'NSDGDP_SA_XDC',"NGDP_XDC","NCP_XDC","NCGG_XDC","NFI_XDC","NINV_XDC","NX_XDC","NM_XDC","NSDGDP_XDC","FMA_XDC","FMB_XDC","FMA_USD","FMB_USD","ENDE_XDC_USD_RATE","FITB_PA","FIGB_PA","PCPI_IX","LWR_IX","LUR_PT"]
indicator = search_id[search_id.input_code.isin(indicator_id)]
indicator

,input_code,description
6,IAFR_BP6_USD,"International Investment Positions, Net acquisition of financial assets (with Fund Record), US Dollars"
45,NINV_XDC,"Changes in Inventories, Nominal, Domestic Currency"
46,NINV_SA_XDC,"Changes in Inventories, Nominal, Seasonally Adjusted, Domestic Currency"
99,BEF_BP6_USD,"Balance of Payments, Exceptional financing, US Dollars"
106,ENDE_XDC_USD_RATE,"Exchange Rates, Domestic Currency per U.S. Dollar, End of Period, Rate"
128,NX_XDC,"Exports of Goods and Services, Nominal, Domestic Currency"
129,NX_SA_XDC,"Exports of Goods and Services, Nominal, Seasonally Adjusted, Domestic Currency"
235,FIGB_PA,"Financial, Interest Rates, Government Securities, Government Bonds, Percent per annum"
242,FITB_PA,"Financial, Interest Rates, Government Securities, Treasury Bills, Percent per annum"
699,NCGG_XDC,"General Government Final Consumption Expenditure, Nominal, Domestic Currency"
700,NCGG_SA_XDC,"General Government Final Consumption Expenditure, Nominal, Seasonally Adjusted, Domestic Currency"
713,NGDP_XDC,"Gross Domestic Product, Nominal, Domestic Currency"
714,NGDP_SA_XDC,"Gross Domestic Product, Nominal, Seasonally Adjusted, Domestic Currency"
733,NFI_XDC,"Gross Fixed Capital Formation, Nominal, Domestic Currency"
734,NFI_SA_XDC,"Gross Fixed Capital Formation, Nominal, Seasonally Adjusted, Domestic Currency"
751,NM_XDC,"Imports of Goods and Services, Nominal, Domestic Currency"
752,NM_SA_XDC,"Imports of Goods and Services, Nominal, Seasonally Adjusted, Domestic Currency"
809,LUR_PT,"Labor Markets, Unemployment Rate, Percent"
812,LWR_IX,"Labor Markets, Wage Rates, Index"
815,ILFR_BP6_USD,"International Investment Positions, Net incurrence of liabilities, US Dollars"
925,FMA_XDC,"Monetary, Base Money, Domestic Currency"
928,FMA_USD,"Monetary, Base Money, US Dollars"
938,FMB_XDC,"Monetary, Broad Money, Domestic Currency"
946,FMB_USD,"Monetary, Broad Money, US Dollars"
1014,FASF_XDC,"Monetary, Central Bank Survey, Net Foreign Assets, Domestic Currency"
1021,FASF_USD,"Monetary, Central Bank Survey, Net Foreign Assets, US Dollars"
1622,PCPI_IX,"Prices, Consumer Price Index, All items, Index"
1626,PXP_IX,"Prices, Export Price Index, All Commodities, Index"
1627,PMP_IX,"Prices, Import Price Index, All Commodities, Index"
1633,NCP_XDC,"Private Sector Final Consumption Expenditure, Nominal, Domestic Currency"
1634,NCP_SA_XDC,"Private Sector Final Consumption Expenditure, Nominal, Seasonally Adjusted, Domestic Currency"
1645,NSDGDP_XDC,"Statistical Discrepancy, Nominal, Domestic Currency"
1646,NSDGDP_SA_XDC,"Statistical Discrepancy, Nominal, Seasonally Adjusted, Domestic Currency"
1652,BKAA_BP6_USD,"Balance of Payments, Supplementary Items, Capital Account (Excludes Reserves and Related Items), US Dollars"
1654,BCAXF_BP6_USD,"Balance of Payments, Supplementary Items, Current Account, Net (excluding exceptional financing), US Dollars"
1659,BOPFR_BP6_USD,"Balance of Payments, Supplementary Items, Errors and Omissions (with Fund Record), US Dollars"
1660,BFXF_BP6_USD,"Balance of Payments, Supplementary Items, Financial Account, Net (excluding exceptional financing), US Dollars"
1669,BTRUE_BP6_USD,"Balance of Payments, Supplementary Items, Reserves and related items, US Dollars"

In [14]:
# Significantly shorter Notation--> Not final version, but best describes the raw data

# This i will use latter to make the columns of the final output more readable...

# Note: Exceptional financing---> Argentia y alianza latinoamericana
indicator_swapper = ["IIP Net Assets,C,USD","IIP Net Liabilities,C,USD","Current Accounnt (Excluding Exceptional Financing),C,USD","Capital Account (Excluding Reserves and related items),C,USD","Financial Account (Excluding Exceptional Financing),C,USD","(BOP)Reserves and realeated items (includes itself Exceptional Financing),C,USD","(BOP) Exceptioanl Financing,C,USD","Net Foreign Assets (Reserves CB),C,USD","Net Foreign Assets (Reserves CB),C,LC","(BOP)Errors and Omissions,C,USD","Exports Price Index","Imporrts Price Index","GDP,SA,C,LC","Consumtion,SA,C,LC","Goverment,SA,C,LC","Investment,SA,C,LC","Change in Inventory Value,SA,C,LC","Exports,SA,C,LC","Imports,SA,C,LC","(NA)Errors and Omissions,NSA,C,LC","GDP,NSA,C,LC","Consumtion,NSA,C,LC","Goverment,NSA,C,LC","Investment,NSA,C,LC","Change in Inventory Value,NSA,C,LC","Exports,NSA,C,LC","Imports,NSA,C,LC","(NA)Errors and Omissions,NSA,C,LC","Base Money,M0,C,LC","Broad Money,M3,C,LC","Base Moeny,M0,C,USD","Broad Money,M3,C,USD","End of Period LC to USD","Short Term Bonds Rate","Long Term Bonds Rate","CPI","Wage Rates Index","Unemployment Rate"]
indicator_swapper_easier = ["IIP(A),USD","IIP(L),USD","CA(-Exceptional Financing),USD","KA(-Reserves and realted items),USD","FA(-Exceptional Financing),USD","(BOP)Reserves and realted items,USD","(BOP) Exceptional Financing,USD","CB Net Foreign Assets,C,USD","CB Net Foreign Assets,C,LC","(BOP)EO,USD","PX Index","PM Index","GDP,SA,LC","C,SA,LC","G,SA,LC","I,SA,LC","Change in Inventory Value,SA,LC","X,SA,LC","M,SA,LC","(NA)EO,SA,LC","GDP,NSA,LC","C,NSA,LC","G,NSA,LC","I,NSA,LC","Change in Inventory Value,NSA,LC","X,NSA,LC","M,NSA,LC","(NA)EO,NSA,LC","M0,LC","M3,LC","M0,USD","M3,USD","LC to USD","Short Term Bond Rate","Long Term Bond Rate","CPI","Wage Rate Index","U"]
indicator_way_shorter_notation = {'BCAXF_BP6_USD': 'CA(-EF),USD',
 'BEF_BP6_USD': '(BOF)EF,USD',
 'BFXF_BP6_USD': 'FA(-EF),USD',
 'BKAA_BP6_USD': 'CA(-R&RI),USD',
 'BOPFR_BP6_USD': 'E&O,USD',
 'BTRUE_BP6_USD': '(BOF)R&RI(EF is in here as well),USD',
 'ENDE_XDC_USD_RATE': 'ER,EoP,LC/USD',
 'FASF_USD': 'Net Financial Assets(CB Reserves),USD',
 'FASF_XDC': 'Net Financial Assets(CB Reserves),LC',
 'FIGB_PA': 'i,LTB,PT per Annum',
 'FITB_PA': 'i,STB,PT per Annum',
 'FMA_USD': 'M0,USD',
 'FMA_XDC': 'M0,LC',
 'FMB_USD': 'M3,USD',
 'FMB_XDC': 'M3,LC',
 'IAFR_BP6_USD': 'IIP NA,USD',
 'ILFR_BP6_USD': 'IIP NL,USD',
 'LUR_PT': 'U,PT',
 'LWR_IX': 'W,IX',
 'NCGG_SA_XDC': 'G,SA,LC',
 'NCGG_XDC': 'G,NSA,LC',
 'NCP_SA_XDC': 'C,SA,LC',
 'NCP_XDC': 'C,NSA,LC',
 'NFI_SA_XDC': 'I,SA,LC',
 'NFI_XDC': 'I,NSA,LC',
 'NGDP_SA_XDC': 'GDP,SA,LC',
 'NGDP_XDC': 'GDP,NSA,LC',
 'NINV_SA_XDC': 'Î”Inventory,SA,LC',
 'NINV_XDC': 'Î”Invtory Value,NSA,LC',
 'NM_SA_XDC': 'M,SA,LC',
 'NM_XDC': 'M,NSA,LC',
 'NSDGDP_SA_XDC': '(NA)E&O,NSA,LC',
 'NSDGDP_XDC': '(NA)E&O,NSA,LC',
 'NX_SA_XDC': 'X,SA,LC',
 'NX_XDC': 'X,NSA,LC',
 'PCPI_IX': 'CPI',
 'PMP_IX': 'PM,IX',
 'PXP_IX': 'PX,IX'}

indicator_dict= {'BCAXF_BP6_USD': 'Balance of Payments, Supplementary Items, Current Account, Net (excluding exceptional financing), US Dollars',
 'BEF_BP6_USD': 'Balance of Payments, Exceptional financing, US Dollars',
 'BFXF_BP6_USD': 'Balance of Payments, Supplementary Items, Financial Account, Net (excluding exceptional financing), US Dollars',
 'BKAA_BP6_USD': 'Balance of Payments, Supplementary Items, Capital Account (Excludes Reserves and Related Items), US Dollars',
 'BOPFR_BP6_USD': 'Balance of Payments, Supplementary Items, Errors and Omissions (with Fund Record), US Dollars',
 'BTRUE_BP6_USD': 'Balance of Payments, Supplementary Items, Reserves and related items, US Dollars',
 'ENDE_XDC_USD_RATE': 'Exchange Rates, Domestic Currency per U.S. Dollar, End of Period, Rate',
 'FASF_USD': 'Monetary, Central Bank Survey, Net Foreign Assets, US Dollars',
 'FASF_XDC': 'Monetary, Central Bank Survey, Net Foreign Assets, Domestic Currency',
 'FIGB_PA': 'Financial, Interest Rates, Government Securities, Government Bonds, Percent per annum',
 'FITB_PA': 'Financial, Interest Rates, Government Securities, Treasury Bills, Percent per annum',
 'FMA_USD': 'Monetary, Base Money, US Dollars',
 'FMA_XDC': 'Monetary, Base Money, Domestic Currency',
 'FMB_USD': 'Monetary, Broad Money, US Dollars',
 'FMB_XDC': 'Monetary, Broad Money, Domestic Currency',
 'IAFR_BP6_USD': 'International Investment Positions, Net acquisition of financial assets (with Fund Record), US Dollars',
 'ILFR_BP6_USD': 'International Investment Positions, Net incurrence of liabilities, US Dollars',
 'LUR_PT': 'Labor Markets, Unemployment Rate, Percent',
 'LWR_IX': 'Labor Markets, Wage Rates, Index',
 'NCGG_SA_XDC': 'General Government Final Consumption Expenditure, Nominal, Seasonally Adjusted, Domestic Currency',
 'NCGG_XDC': 'General Government Final Consumption Expenditure, Nominal, Domestic Currency',
 'NCP_SA_XDC': 'Private Sector Final Consumption Expenditure, Nominal, Seasonally Adjusted, Domestic Currency',
 'NCP_XDC': 'Private Sector Final Consumption Expenditure, Nominal, Domestic Currency',
 'NFI_SA_XDC': 'Gross Fixed Capital Formation, Nominal, Seasonally Adjusted, Domestic Currency',
 'NFI_XDC': 'Gross Fixed Capital Formation, Nominal, Domestic Currency',
 'NGDP_SA_XDC': 'Gross Domestic Product, Nominal, Seasonally Adjusted, Domestic Currency',
 'NGDP_XDC': 'Gross Domestic Product, Nominal, Domestic Currency',
 'NINV_SA_XDC': 'Changes in Inventories, Nominal, Seasonally Adjusted, Domestic Currency',
 'NINV_XDC': 'Changes in Inventories, Nominal, Domestic Currency',
 'NM_SA_XDC': 'Imports of Goods and Services, Nominal, Seasonally Adjusted, Domestic Currency',
 'NM_XDC': 'Imports of Goods and Services, Nominal, Domestic Currency',
 'NSDGDP_SA_XDC': 'Statistical Discrepancy, Nominal, Seasonally Adjusted, Domestic Currency',
 'NSDGDP_XDC': 'Statistical Discrepancy, Nominal, Domestic Currency',
 'NX_SA_XDC': 'Exports of Goods and Services, Nominal, Seasonally Adjusted, Domestic Currency',
 'NX_XDC': 'Exports of Goods and Services, Nominal, Domestic Currency',
 'PCPI_IX': 'Prices, Consumer Price Index, All items, Index',
 'PMP_IX': 'Prices, Import Price Index, All Commodities, Index',
 'PXP_IX': 'Prices, Export Price Index, All Commodities, Index'}

In [18]:
# Nice Aggregator function to go faster
def data_aggregator(indicator_id, freq_id=["A", "Q", "M"], database_id="IFS", ref_area_id=None,window_size=8):
    """
    Aggregates data from a specific dataset based on the given parameters.

    Parameters:
    - indicator (list): List of indicator codes to retrieve data for.
    - freq (list, optional): The frequency of the data. Defaults to ["A", "Q", "M"].
    - database_id (str, optional): The database ID to retrieve data from. Defaults to "IFS".
    - ref_area (str or list, optional): The reference area code or a list of reference area codes to retrieve data for. Defaults to None.

    Returns:
    - data (pandas.DataFrame): The aggregated data.

    """
    # Load the dataset parameters
    import time
    dataset_params = imfp.imf_parameters(database_id) # Load this particular dataset all possible features
    search_id = dataset_params["indicator"]
    freq = dataset_params["freq"][dataset_params["freq"].input_code.isin(freq_id)]
    
    # Set the ref_area parameters
    if ref_area_id != None:
        ref_area = dataset_params["ref_area"][dataset_params["ref_area"].input_code.isin(ref_area_id)]
    else:
        ref_area = dataset_params["ref_area"]
    
    # Set the indicator parameters
    indicator_id = indicator_id
    
    # Set the data parameters
    data_params = dict(zip(dataset_params.keys(), [[0]] * len(dataset_params.keys())))
    data_params["freq"] = freq
    data_params["ref_area"] = ref_area
    
    #Window size of loop
    indicator_sub_list = [indicator_id[i:i+window_size] for i in range(0, len(indicator_id), window_size)]
    
    # Retrieve the data and aggregate it
    for i, indicator in enumerate(indicator_sub_list):
        #imfp.set_imf_app_name(f"my_custom_app_name_{i}")
        indicator = search_id[search_id.input_code.isin(indicator)]
        data_params["indicator"] = indicator
        data_0 = imfp.imf_dataset(database_id=database_id, parameters=data_params)
        if i == 0:
            data = data_0.copy()
        else:
            data=pd.concat([data, data_0])
        time.sleep(5)
    return data

In [41]:
# Execute the data gathering algorithm
# Divide the list into sublists

def divide_list(lst, n=6):
    """Divide a list into n sublists."""
    # Calculate the size of each sublist
    sublist_size = len(lst) // n
    # Create sublists
    sublists = [lst[i:i + sublist_size] for i in range(0, len(lst), sublist_size)]
    # If there are remaining elements, add them to the last sublist
    if len(lst) % n:
        sublists[-1].extend(lst[-sublist_size * n:])
    return sublists
ref_area_id_sublists = divide_list(ref_area_id) 


for i,ref_area_id_chunk in enumerate(ref_area_id_sublists):
    if i==0:
        data = data_aggregator(indicator_id,ref_area_id=ref_area_id_chunk,window_size=9)
    if i>0:
        data = pd.concat([data,data_aggregator(indicator_id,ref_area_id=ref_area_id_chunk,window_size=9)],axis=0)
data

,freq,ref_area,indicator,unit_mult,time_format,time_period,obs_value,obs_status,base_year
0,A,BI,FASF_XDC,6,P1Y,2001,1184.63574516535,NaN,NaN
1,A,BI,FASF_XDC,6,P1Y,2002,6616.79247350301,NaN,NaN
2,A,BI,FASF_XDC,6,P1Y,2003,15385.1394098616,NaN,NaN
3,A,BI,FASF_XDC,6,P1Y,2004,-2882.37218691365,NaN,NaN
4,A,BI,FASF_XDC,6,P1Y,2005,28985.9530423061,NaN,NaN
...,...,...,...,...,...,...,...,...,...
67,M,UA,LUR_PT,0,P1M,2015-12,9.143,NaN,NaN
68,M,UA,LUR_PT,0,P1M,2016-03,9.917,NaN,NaN
69,M,UA,LUR_PT,0,P1M,2016-06,8.956,NaN,NaN
70,M,UA,LUR_PT,0,P1M,2016-09,8.846,NaN,NaN
71,M,UA,LUR_PT,0,P1M,2016-12,9.681,NaN,NaN

In [54]:
# Check for avaiable memory
data.info(memory_usage="deep")
import psutil
available_memory_bytes = psutil.virtual_memory().available
available_memory_mb = available_memory_bytes / (2**20)
print(f"Available memory: {available_memory_mb:.2f} MB")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 867454 entries, 0 to 71
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   freq         867454 non-null  object
 1   ref_area     867454 non-null  object
 2   indicator    867454 non-null  object
 3   unit_mult    867454 non-null  object
 4   time_format  867454 non-null  object
 5   time_period  867454 non-null  object
 6   obs_value    867080 non-null  object
 7   obs_status   5478 non-null    object
 8   base_year    193251 non-null  object
dtypes: object(9)
memory usage: 425.5 MB
Available memory: 4302.21 MB

In [45]:
# Now, lets make the output a little bit more readable!!
import numpy as np

data_ajusted = data.copy()

# I believe this can be all eliminated up to data_ajusted["obs_value"]=...
# Convert the time_period into time_stamps
def convert_to_datatime(row): # Basically, to each row value of the series data_ajusted["time_period"], apply the transformation
    if "-" in row or "Q" in row:
        return pd.to_datetime(row).strftime('%Y-%m-%d')
    else:
        return pd.to_datetime(row).year
data_ajusted["time_period"] = data_ajusted["time_period"].apply(convert_to_datatime) # Apply the transformation to each row.

# Obs_value to numeric + make the unit mult correct: The unit mult represents the number of zeros to add to the obs_value
data_ajusted["obs_value"] = data_ajusted["obs_value"].astype(float)
data_ajusted["unit_mult"] = data_ajusted["unit_mult"].astype(int)
data_ajusted["obs_value"] = data_ajusted["obs_value"] * 10 ** data_ajusted["unit_mult"]
# Separate data by frequency, then by reference area then by time period
data_ajusted = data_ajusted.pivot_table(
    index=["freq","ref_area","time_period"],
    columns=["indicator"],
    values=["obs_value"]
)


# Ajust to USD terms everything
data_ajusted.columns=data_ajusted.columns.droplevel(0)
data_ajusted.reset_index(inplace=True)
for column in data_ajusted.columns:
    if "XDC" in column and not "ENDE" in column:
        data_ajusted[column] = data_ajusted[column]*(1/data_ajusted["ENDE_XDC_USD_RATE"])
data_ajusted.set_index(["freq","ref_area","time_period"],inplace=True)
data_ajusted.replace(0, np.nan, inplace=True)
data_ajusted

indicator                  BCAXF_BP6_USD  BEF_BP6_USD  BFXF_BP6_USD  \
freq ref_area time_period
A    AD       2000                   NaN          NaN           NaN
              2001                   NaN          NaN           NaN
              2002                   NaN          NaN           NaN
              2003                   NaN          NaN           NaN
              2004                   NaN          NaN           NaN
...                                  ...          ...           ...
Q    ZW       2022-10-01             NaN          NaN           NaN
              2023-01-01             NaN          NaN           NaN
              2023-04-01             NaN          NaN           NaN
              2023-07-01             NaN          NaN           NaN
              2023-10-01             NaN          NaN           NaN

indicator                  BKAA_BP6_USD  BOPFR_BP6_USD  BTRUE_BP6_USD  \
freq ref_area time_period
A    AD       2000                  NaN            NaN            NaN
              2001                  NaN            NaN            NaN
              2002                  NaN            NaN            NaN
              2003                  NaN            NaN            NaN
              2004                  NaN            NaN            NaN
...                                 ...            ...            ...
Q    ZW       2022-10-01            NaN            NaN            NaN
              2023-01-01            NaN            NaN            NaN
              2023-04-01            NaN            NaN            NaN
              2023-07-01            NaN            NaN            NaN
              2023-10-01            NaN            NaN            NaN

indicator                  ENDE_XDC_USD_RATE  FASF_USD      FASF_XDC  FIGB_PA  \
freq ref_area time_period
A    AD       2000                       NaN       NaN           NaN      NaN
              2001                       NaN       NaN           NaN      NaN
              2002                       NaN       NaN           NaN      NaN
              2003                       NaN       NaN           NaN      NaN
              2004                       NaN       NaN           NaN      NaN
...                                      ...       ...           ...      ...
Q    ZW       2022-10-01            684.3390       NaN -4.063544e+09      NaN
              2023-01-01            929.8618       NaN -4.033189e+09      NaN
              2023-04-01           5739.7961       NaN -3.625484e+09      NaN
              2023-07-01           5466.7466       NaN -3.717735e+09      NaN
              2023-10-01           6104.7226       NaN -3.727620e+09      NaN

indicator                  ...  NINV_XDC  NM_SA_XDC  NM_XDC  NSDGDP_SA_XDC  \
freq ref_area time_period  ...
A    AD       2000         ...       NaN        NaN     NaN            NaN
              2001         ...       NaN        NaN     NaN            NaN
              2002         ...       NaN        NaN     NaN            NaN
              2003         ...       NaN        NaN     NaN            NaN
              2004         ...       NaN        NaN     NaN            NaN
...                        ...       ...        ...     ...            ...
Q    ZW       2022-10-01   ...       NaN        NaN     NaN            NaN
              2023-01-01   ...       NaN        NaN     NaN            NaN
              2023-04-01   ...       NaN        NaN     NaN            NaN
              2023-07-01   ...       NaN        NaN     NaN            NaN
              2023-10-01   ...       NaN        NaN     NaN            NaN

indicator                  NSDGDP_XDC  NX_SA_XDC  NX_XDC       PCPI_IX  \
freq ref_area time_period
A    AD       2000                NaN        NaN     NaN           NaN
              2001                NaN        NaN     NaN           NaN
              2002                NaN        NaN     NaN           NaN
              2003                NaN        NaN     NaN           NaN
              2004                NaN        NaN     NaN           NaN
...                               ...        ...     ...           ...
Q    ZW       2022-10-01          NaN        NaN     NaN  14281.538789
              2023-01-01          NaN        NaN     NaN  14422.112249
              2023-04-01          NaN        NaN     NaN  20459.366874
              2023-07-01          NaN        NaN     NaN           NaN
              2023-10-01          NaN        NaN     NaN           NaN

indicator                  PMP_IX  PXP_IX
freq ref_area time_period
A    AD       2000            NaN     NaN
              2001            NaN     NaN
              2002            NaN     NaN
              2003            NaN     NaN
              2004            NaN     NaN
...                           ...     ...
Q    ZW       2022-10-01      NaN     NaN
              2023-01-01      NaN     NaN
              2023-04-01      NaN     NaN
              2023-07-01      NaN     NaN
              2023-10-01      NaN     NaN

[209187 rows x 38 columns]

In [46]:
# After LC to USD ajustment---> Actualization of best names!
indicator_way_shorter_notation = {'BCAXF_BP6_USD': 'CA(-EF),USD',
 'BEF_BP6_USD': '(BOF)EF,USD',
 'BFXF_BP6_USD': 'FA(-EF),USD',
 'BKAA_BP6_USD': 'CA(-R&RI),USD',
 'BOPFR_BP6_USD': 'E&O,USD',
 'BTRUE_BP6_USD': '(BOF)R&RI(EF here as well),USD',
 'ENDE_XDC_USD_RATE': 'ER,EoP,LC_USD(LC)',
 'FASF_USD': 'NFA,USD',
 'FASF_XDC': 'NFA,USD(LC)',
 'FIGB_PA': 'i,LTB,PT per Annum',
 'FITB_PA': 'i,STB,PT per Annum',
 'FMA_USD': 'M0,USD',
 'FMA_XDC': 'M0,USD(LC)',
 'FMB_USD': 'M3,USD',
 'FMB_XDC': 'M3,USD(LC)',
 'IAFR_BP6_USD': 'IIP NA,USD',
 'ILFR_BP6_USD': 'IIP NL,USD',
 'LUR_PT': 'U,PT',
 'LWR_IX': 'W,IX',
 'NCGG_SA_XDC': 'G,SA,USD(LC)',
 'NCGG_XDC': 'G,NSA,USD(LC)',
 'NCP_SA_XDC': 'C,SA,USD(LC)',
 'NCP_XDC': 'C,NSA,USD(LC)',
 'NFI_SA_XDC': 'I,SA,USD(LC)',
 'NFI_XDC': 'I,NSA,USD(LC)',
 'NGDP_SA_XDC': 'GDP,SA,USD(LC)',
 'NGDP_XDC': 'GDP,NSA,USD(LC)',
 'NINV_SA_XDC': 'Chg. Invent. Value,SA,USD(LC)',
 'NINV_XDC': 'Chg. Invent. Value,NSA,USD(LC)',
 'NM_SA_XDC': 'M,SA,USD(LC)',
 'NM_XDC': 'M,NSA,USD(LC)',
 'NSDGDP_SA_XDC': '(NA)E&O,NSA,SA,USD(LC)',
 'NSDGDP_XDC': '(NA)E&O,NSA,USD(LC)',
 'NX_SA_XDC': 'X,SA,USD(LC)',
 'NX_XDC': 'X,NSA,USD(LC)',
 'PCPI_IX': 'CPI',
 'PMP_IX': 'PM,IX',
 'PXP_IX': 'PX,IX'}

for key,value in indicator_way_shorter_notation.items():
    if 'XDC' in key  and 'USD(LC)' not in value:
        indicator_way_shorter_notation[key] += '(LC)'
data_ajusted.rename(columns=indicator_way_shorter_notation,inplace=True)
data_ajusted["i,LTB,PT per Annum"].dropna().index.get_level_values(1).unique()
data_ajusted

indicator                  CA(-EF),USD  (BOF)EF,USD  FA(-EF),USD  \
freq ref_area time_period
A    AD       2000                 NaN          NaN          NaN
              2001                 NaN          NaN          NaN
              2002                 NaN          NaN          NaN
              2003                 NaN          NaN          NaN
              2004                 NaN          NaN          NaN
...                                ...          ...          ...
Q    ZW       2022-10-01           NaN          NaN          NaN
              2023-01-01           NaN          NaN          NaN
              2023-04-01           NaN          NaN          NaN
              2023-07-01           NaN          NaN          NaN
              2023-10-01           NaN          NaN          NaN

indicator                  CA(-R&RI),USD  E&O,USD  \
freq ref_area time_period
A    AD       2000                   NaN      NaN
              2001                   NaN      NaN
              2002                   NaN      NaN
              2003                   NaN      NaN
              2004                   NaN      NaN
...                                  ...      ...
Q    ZW       2022-10-01             NaN      NaN
              2023-01-01             NaN      NaN
              2023-04-01             NaN      NaN
              2023-07-01             NaN      NaN
              2023-10-01             NaN      NaN

indicator                  (BOF)R&RI(EF here as well),USD  ER,EoP,LC_USD(LC)  \
freq ref_area time_period
A    AD       2000                                    NaN                NaN
              2001                                    NaN                NaN
              2002                                    NaN                NaN
              2003                                    NaN                NaN
              2004                                    NaN                NaN
...                                                   ...                ...
Q    ZW       2022-10-01                              NaN           684.3390
              2023-01-01                              NaN           929.8618
              2023-04-01                              NaN          5739.7961
              2023-07-01                              NaN          5466.7466
              2023-10-01                              NaN          6104.7226

indicator                  NFA,USD   NFA,USD(LC)  i,LTB,PT per Annum  ...  \
freq ref_area time_period                                             ...
A    AD       2000             NaN           NaN                 NaN  ...
              2001             NaN           NaN                 NaN  ...
              2002             NaN           NaN                 NaN  ...
              2003             NaN           NaN                 NaN  ...
              2004             NaN           NaN                 NaN  ...
...                            ...           ...                 ...  ...
Q    ZW       2022-10-01       NaN -4.063544e+09                 NaN  ...
              2023-01-01       NaN -4.033189e+09                 NaN  ...
              2023-04-01       NaN -3.625484e+09                 NaN  ...
              2023-07-01       NaN -3.717735e+09                 NaN  ...
              2023-10-01       NaN -3.727620e+09                 NaN  ...

indicator                  Chg. Invent. Value,NSA,USD(LC)  M,SA,USD(LC)  \
freq ref_area time_period
A    AD       2000                                    NaN           NaN
              2001                                    NaN           NaN
              2002                                    NaN           NaN
              2003                                    NaN           NaN
              2004                                    NaN           NaN
...                                                   ...           ...
Q    ZW       2022-10-01                              NaN           NaN
              2023-01-01                              NaN           NaN
              2023-04-01                              NaN           NaN
              2023-07-01                              NaN           NaN
              2023-10-01                              NaN           NaN

indicator                  M,NSA,USD(LC)  (NA)E&O,NSA,SA,USD(LC)  \
freq ref_area time_period
A    AD       2000                   NaN                     NaN
              2001                   NaN                     NaN
              2002                   NaN                     NaN
              2003                   NaN                     NaN
              2004                   NaN                     NaN
...                                  ...                     ...
Q    ZW       2022-10-01             NaN                     NaN
              2023-01-01             NaN                     NaN
              2023-04-01             NaN                     NaN
              2023-07-01             NaN                     NaN
              2023-10-01             NaN                     NaN

indicator                  (NA)E&O,NSA,USD(LC)  X,SA,USD(LC)  X,NSA,USD(LC)  \
freq ref_area time_period
A    AD       2000                         NaN           NaN            NaN
              2001                         NaN           NaN            NaN
              2002                         NaN           NaN            NaN
              2003                         NaN           NaN            NaN
              2004                         NaN           NaN            NaN
...                                        ...           ...            ...
Q    ZW       2022-10-01                   NaN           NaN            NaN
              2023-01-01                   NaN           NaN            NaN
              2023-04-01                   NaN           NaN            NaN
              2023-07-01                   NaN           NaN            NaN
              2023-10-01                   NaN           NaN            NaN

indicator                           CPI  PM,IX  PX,IX
freq ref_area time_period
A    AD       2000                  NaN    NaN    NaN
              2001                  NaN    NaN    NaN
              2002                  NaN    NaN    NaN
              2003                  NaN    NaN    NaN
              2004                  NaN    NaN    NaN
...                                 ...    ...    ...
Q    ZW       2022-10-01   14281.538789    NaN    NaN
              2023-01-01   14422.112249    NaN    NaN
              2023-04-01   20459.366874    NaN    NaN
              2023-07-01            NaN    NaN    NaN
              2023-10-01            NaN    NaN    NaN

[209187 rows x 38 columns]

In [48]:
# Generate Combined Variables
from openpyxl import Workbook
from openpyxl import load_workbook
boost=1.2
strip=2.2
def create_empty_excel(file_path):
    # Create a new workbook
    wb = Workbook()
    # Save the workbook to the specified file path
    wb.save(file_path)
anual_obs_threshold = 15
quarterly_obs_threshold = 60
monthly_obs_threshold = 170
anual_combined_variable = pd.DataFrame()
quarterly_combined_variable = pd.DataFrame()
monthly_combined_variable = pd.DataFrame()

anual_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Natioanl Accounting Variables Anual.xlsx'
quarterly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Natioanl Accounting Variables Quarterly.xlsx'
monthly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Natioanl Accounting Variables Monthly.xlsx'
create_empty_excel(anual_url)
create_empty_excel(quarterly_url)   
create_empty_excel(monthly_url)

# Generate Individal Variables
for freq in data_ajusted.index.get_level_values(0).unique():
    freq_data_ajusted = data_ajusted.loc[freq]
    if freq == "A":
        filter = anual_obs_threshold
    elif freq == "Q":
        filter = quarterly_obs_threshold
    else:
        filter = monthly_obs_threshold
    for variable_name in freq_data_ajusted.columns:
        variable =freq_data_ajusted[[variable_name]]
        variable=freq_data_ajusted[[variable_name]].reset_index().pivot(index="time_period",columns="ref_area").dropna(axis=1,thresh=filter,subset=freq_data_ajusted[[variable_name]].reset_index().pivot(index="time_period",columns="ref_area").tail(int(filter*boost)).index)
        variable = variable.tail(int(filter*strip)).dropna(axis=1,thresh=filter*(boost+0.3))
        #variable.interpolate(method='linear',axis=0, inplace=True)
        if freq == "A" and variable.shape[0]!=0:
            anual_combined_variable=pd.concat([anual_combined_variable,variable],axis=1)
        elif freq == "Q" and variable.shape[0]!=0:
            quarterly_combined_variable=pd.concat([quarterly_combined_variable,variable],axis=1)
        elif freq == "M" and variable.shape[0]!=0:
            monthly_combined_variable=pd.concat([monthly_combined_variable,variable],axis=1)
        variable.columns = variable.columns.droplevel(0)
        if freq == "A" and variable.shape[0]!=0:
            with pd.ExcelWriter(anual_url, engine='openpyxl',mode="a") as writer:
                variable.to_excel(writer, sheet_name=variable_name)
        elif freq == "Q" and variable.shape[0]!=0:
            with pd.ExcelWriter(quarterly_url, engine='openpyxl',mode="a") as writer:
                variable.to_excel(writer, sheet_name=variable_name)
        elif freq == "M" and variable.shape[0]!=0:
            with pd.ExcelWriter(monthly_url, engine='openpyxl',mode="a") as writer:
                variable.to_excel(writer, sheet_name=variable_name)

workbook = load_workbook(anual_url)
workbook.remove(workbook[workbook.sheetnames[0]])
workbook.save(anual_url)
workbook = load_workbook(quarterly_url)
workbook.remove(workbook[workbook.sheetnames[0]])
workbook.save(quarterly_url)
workbook = load_workbook(monthly_url)
workbook.remove(workbook[workbook.sheetnames[0]])
workbook.save(monthly_url)

anual_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Aggregated+Annual+Natioanl Accounting Variables.xlsx'
quarterly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Aggregated+Quarterly+Natioanl Accounting Variables.xlsx'
monthly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Variables Data\Aggregated+Monthly+Natioanl Accounting Variables.xlsx'

if anual_combined_variable.shape[0]!=0:
    with pd.ExcelWriter(anual_url, engine='openpyxl',mode="w") as writer:
        anual_combined_variable.to_excel(writer, sheet_name="Anual Agregated Variables")
        anual_combined_variable.index = anual_combined_variable.index.astype('int64')
        anual_combined_variable = anual_combined_variable.replace(0,np.nan)
        anual_combined_variable = anual_combined_variable.interpolate(method='quadratic',limit_direction='both',limit_area='inside',axis=0)
        anual_combined_variable.to_excel(writer, sheet_name="Anual Agreg Variables(F)")
        anual_combined_variable.dropna().to_excel(writer, sheet_name="Anual Agreg Variables(FC)")
if quarterly_combined_variable.shape[0]!=0:
    with pd.ExcelWriter(quarterly_url, engine='openpyxl',mode="w") as writer:
        quarterly_combined_variable.to_excel(writer, sheet_name="Quarterly Agregated Variables")
        quarterly_combined_variable.index = pd.to_datetime(quarterly_combined_variable.index)
        quarterly_combined_variable = quarterly_combined_variable.replace(0,np.nan)
        quarterly_combined_variable=quarterly_combined_variable.interpolate(method='time',limit_direction='both',limit_area='inside',axis=0)
        quarterly_combined_variable.to_excel(writer, sheet_name="Quarterly Agreg Variables(F)")
        quarterly_combined_variable.dropna().to_excel(writer, sheet_name="Quarterly Agreg Variables(FC)")
if monthly_combined_variable.shape[0]!=0:
    with pd.ExcelWriter(monthly_url, engine='openpyxl',mode="w") as writer:
        monthly_combined_variable.to_excel(writer, sheet_name="Monthly Agregated Variables")
        monthly_combined_variable.index = pd.to_datetime(monthly_combined_variable.index)
        monthly_combined_variable = monthly_combined_variable.replace(0,np.nan)
        monmonthly_combined_variable=monthly_combined_variable.interpolate(method='time',limit_direction='both',limit_area='inside',axis=0)
        monmonthly_combined_variable.to_excel(writer, sheet_name="Monthly Agreg Variables(F)")
        monmonthly_combined_variable.dropna().to_excel(writer, sheet_name="Monthly Agreg Variables(FC)")

In [53]:
# Generate by countries data
boost=1.2
strip=2.2

from openpyxl import Workbook
def create_empty_excel(file_path):
    # Create a new workbook
    wb = Workbook()
    # Save the workbook to the specified file path
    wb.save(file_path)
    
anual_obs_threshold = 15
quarterly_obs_threshold = 60
monthly_obs_threshold = 170
agregated_countries_anual = pd.DataFrame()
agregated_countries_quarterly = pd.DataFrame()
agregated_countries_monthly = pd.DataFrame()

anual_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Anual\Aggregated+Anual+Natioanl Accounting Variables Country.xlsx'
quarterly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Quarterly\Aggregated+Quarterly+Natioanl Accounting Countries.xlsx'
monthly_url = r'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Monthly\Aggregated+Monthly+Natioanl Accounting Countries Monthly.xlsx'

for freq in data_ajusted.index.get_level_values(0).unique():
    freq_data_ajusted = data_ajusted.loc[freq]
    if freq == "A":
        filter = anual_obs_threshold
    elif freq == "Q":
        filter = quarterly_obs_threshold
    else:
        filter = monthly_obs_threshold
    for ref_area in freq_data_ajusted.index.get_level_values(0).unique():
        particular_country = freq_data_ajusted.loc[[ref_area]].dropna(axis=1,thresh=filter,subset=freq_data_ajusted.loc[[ref_area]].tail(int(filter*boost)).index)
        particular_country=particular_country.tail(int(filter*strip)).dropna(axis=1,thresh=filter*(boost+0.3))
        particular_country=particular_country.reset_index().set_index("time_period").drop(columns="ref_area")
        column_index=pd.MultiIndex.from_product([[ref_area], particular_country.columns])
        particular_country.columns = column_index
        particular_country=particular_country

        if freq == "A" and particular_country.shape[0]!=0:
            agregated_countries_anual=pd.concat([agregated_countries_anual,particular_country],axis=1)
        elif freq == "Q" and particular_country.shape[0]!=0:
            agregated_countries_quarterly=pd.concat([agregated_countries_quarterly,particular_country],axis=1)
        elif freq == "M" and particular_country.shape[0]!=0:
            agregated_countries_monthly=pd.concat([agregated_countries_monthly,particular_country],axis=1)

        particular_country.T.index.droplevel(0)
        particular_country=particular_country
        
        if freq == "A" and particular_country.shape[0]!=0:
            with pd.ExcelWriter(rf'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Anual\{ref_area}+Annual+Natioanl Accounting Country.xlsx', engine='openpyxl',mode="w") as writer:
                particular_country.to_excel(writer, sheet_name=ref_area)
                particular_country.index = particular_country.index.astype('int64')
                particular_country = particular_country.replace(0,np.nan)
                particular_country = particular_country.interpolate(method='quadratic',limit_direction='both',limit_area='inside',axis=0)
                particular_country.to_excel(writer, sheet_name=ref_area+"(F)")
                particular_country.dropna().to_excel(writer, sheet_name=ref_area+"(FC)")

        elif freq == "Q" and particular_country.shape[0]!=0:
            with pd.ExcelWriter(rf'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Quarterly\{ref_area}+Quarterly+Natioanl Accounting Countries.xlsx', engine='openpyxl',mode="w") as writer:
                particular_country.to_excel(writer, sheet_name=ref_area)
                particular_country.index = pd.to_datetime(particular_country.index)
                particular_country = particular_country.interpolate(method='time',limit_direction='both',limit_area='inside',axis=0)
                particular_country.to_excel(writer, sheet_name=ref_area+"(F)")
                particular_country.dropna().to_excel(writer, sheet_name=ref_area+"(FC)")
        elif freq == "M" and particular_country.shape[0]!=0:
            with pd.ExcelWriter(rf'C:\Users\zeroi\Desktop\Neet Datasets\National Accounts by country\National Accounting Countries Data\Monthly\{ref_area}+Monthly+Natioanl Accounting Countries Monthly.xlsx', engine='openpyxl',mode="w") as writer:
                particular_country.to_excel(writer, sheet_name=ref_area)
                particular_country.index = pd.to_datetime(particular_country.index)
                particular_country = particular_country.interpolate(method='time',limit_direction='both',limit_area='inside',axis=0)
                particular_country.to_excel(writer, sheet_name=ref_area+"(F)")
                particular_country.dropna().to_excel(writer, sheet_name=ref_area+"(FC)")